### ISSUE TITLE
please answer | 

### ISSUE THREAD

**Issue by rfve** [hesham25/Amazon_monitoring_telegramBot#3]
hello,

this script scans only the products on the first page in the categories. how can I configure the script to scrape products from all pages in the category links?

please answer ...

**Comment by hesham25** [comment]
check the line 122.
first I got all available pages count,  the I made a list of all pagination urls

**Comment by rfve** [comment]
I've checked. but it doesn't work with this version. what needs to be done to get the number of pages ?
